### ISSUE TITLE
Double-san in conversations with Yuki

### ISSUE THREAD

**Issue by Cloudrei** [JuicyStandoffishMan/WhiteAlbumRestorationPatch#5]
On various occasions (noticed primarily during Yuki's November 30th Festival date), Yuki seems to refer to Eiji as Ogata-San-San, not sure if this is normal or not, have also not checked if it happens to her with anyone else. On the same day, Touya referred to him as Eiji-san just fine, however

**Comment by Cloudrei** [comment]
Looks like it appears to also happen past the 30th, its also happened on both December 5th and 7th conversations with Yuki

**Comment by JuicyStandoffishMan** [comment]
Good catch :) Looks like it happens in a handful of scripts. Not sure how that happened to begin with, but fixed with a v0.2 patch. If you re-apply it, make sure it's applied to a fresh Script.sdat file.

**Comment by Cloudrei** [comment]
Just tested, haven't noticed the issue at all whatsoever since update, both on previous days and up to 1/3 so far. Thank you!
